Repository nvm-sh/nvm, pull requests merged in 2018-06, with the labels that each got.

#1804 allow user to explicitly opt out of nvm adding the source string
  install.sh
  test/install_script/nvm_detect_profile
Labels: installing nvm

#1830 Prepend instead of changing if shadowed by system dirs (fixes #1652)
  nvm.sh
  test/fast/Unit tests/nvm_change_path
Labels: bugs

#1839 Explain --no-use in installation instructions
  README.md
Labels: informational

#1840 [Docs] add --no-use option to installation
  README.md
Labels: informational
