Repository nvm-sh/nvm, pull requests merged in 2018-11, with the labels that each got.

#1865 Add section on automatic `nvm use` in Bash
  README.md
Labels: informational, shell: bash/sh

#1930 [Docs] improve instructions for manual install
  README.md
Labels: informational, installing nvm

#1925 [docs] update README to fix docker run command flag order
  README.md
Labels: informational

#1938 Allow zsh users to have the nomatch option set
  nvm.sh
Labels: shell: zsh

#1947 Enable ccache on Travis CI to speed up compilation
  .travis.yml
Labels: testing
