Repository nvm-sh/nvm, pull requests merged in 2018-10, with the labels that each got.

#1911 Add support for ZSH_DISABLE_COMPFIX flag.
  bash_completion
Labels: shell: zsh: oh-my-zsh

#1917 Logic for when $METHOD is something unexpected
  install.sh
Labels: installing nvm

#1926 Added fish nvm
  README.md
Labels: shell: fish
