Repository nvm-sh/nvm, pull requests merged in 2018-04, with the labels that each got.

#1775 removed global install on README.md. closes #1773
  README.md
Labels: informational

#1777 Add removal instructions to README.md
  README.md
Labels: informational, installing nvm

#1783 Improve install.sh prompt output, add a new line
  install.sh
Labels: installing nvm

#1786 [Doc] Fix manual install & upgrade guide
  README.md
Labels: informational, installing nvm

#1787 [Doc] Add macOS install script note about Git
  README.md
Labels: OS: Mac OS, informational, installing nvm

#1517 [Refactor] Speedup nvm_list_aliases() / `nvm ls`
  nvm.sh
Labels: performance

#1793 add --tags to git fetch in manual upgrade
  README.md
Labels: informational, installing nvm
