Repository nvm-sh/nvm, pull requests merged in 2018-03, with the labels that each got.

#1751 [Fix] Use `nvm_echo` instead of `echo` directly
  nvm.sh
Labels: bugs

#1753 [Docs] Fix some typos
  .github/ISSUE_TEMPLATE.md
  README.md
Labels: informational

#1759 Reduce bash_completion startup time
  bash_completion
Labels: performance
