Repository nvm-sh/nvm, pull requests merged in 2019-01, with the labels that each got.

#1974 Improve phrasing of 'nvm current'
  nvm.sh
Labels: informational

#1981 README: clarify how to specify default packages
  README.md
Labels: informational

#1986 [Fix] Make installation less restrictive when NVM_DIR is set
  install.sh
Labels: installing nvm

#1989 [Fix] Add missing io.js installing message
  nvm.sh
  test/installation_iojs/install from binary
Labels: bugs, installing node, io.js

#1992 update error message
  nvm.sh
  test/fast/Aliases/"nvm unalias" should not accept aliases with names equal to built-in alias
Labels: informational
