Repository nvm-sh/nvm, pull requests merged in 2020-08, with the labels that each got.

#2271 [readme] Add documentation for LTS updates which reinstall existing packages
  README.md
Labels: informational, installing node

#2274 Add --alias and --default to Install
  nvm.sh
  test/installation_node/install with --alias
  test/installation_node/install with --default
Labels: feature requests, installing node

#1929 [New] adding default and alias option to `nvm install`
  nvm.sh
  test/installation_node/install with --alias
  test/installation_node/install with --default
Labels: feature requests, installing node

#2263 Update docs and add warning for 'nvm is not compatible with the npm config "prefix" option' edgecase error on Mac OS
  README.md
  nvm.sh
Labels: OS: Mac OS, informational

#2277 [Fix] ensure `--help` is intercepted on any command
  nvm.sh
  test/fast/Unit tests/nvm_check_for_help
Labels: feature requests

#2282 [readme] Mention problem with windows cmd echo
  README.md
Labels: OS: windows, informational

#2286 Small nvm_auto optimization
  nvm.sh
Labels: performance

#2294 Update README.md for LTS upgrade
  README.md
Labels: informational
