Repository nvm-sh/nvm, pull requests merged in 2020-07, with the labels that each got.

#2248 Update macOS troubleshooting w/ 10.15 zsh default
  README.md
Labels: OS: Mac OS, informational

#2252 Fix bug in fish example script
  README.md
Labels: informational, shell: fish

#2156 nvm.sh: Add more xz platform support checks
  nvm.sh
Labels: OS: Mac OS, installing node

#2242 Update nvm.sh help command to better explain <version> optionality
  nvm.sh
Labels: informational
