Repository nvm-sh/nvm, pull requests merged in 2020-12, with the labels that each got.

#2104 Make some updates in Travis config
  .travis.yml
Labels: testing

#2205 [Docs] git install document update, sourcing nvm
  README.md
Labels: informational, installing nvm, needs followup

#2388 [Docs]: Updated README.md to include homebrew unsecure dirs warning
  README.md
Labels: OS: Mac OS, informational, shell: zsh

#2393 [Fix]: Fixes errors with compinit and bashcompinit
  bash_completion
Labels: shell: zsh
