Repository nvm-sh/nvm, pull requests merged in 2021-04, with the labels that each got.

#2469 nvm_get_arch(): fix for arm64 kernel running armv7l userland
  nvm.sh
  test/fast/Unit tests/nvm_get_arch
Labels: OS: Raspberry Pi, bugs

#2479 Improve README about Macs with M1 chips
  README.md
Labels: OS: Mac OS, informational

#2391 Make it work on Windows with WSL, MSYS, Cygwin
  .github/workflows/windows-npm.yml
  README.md
  nvm.sh
  test/fast/Unit tests/nvm_get_artifact_compression
  test/fast/Unit tests/nvm_install_binary_extract
  test/fast/Unit tests/nvm_is_version_installed
Labels: OS: windows, feature requests, installing node, installing nvm

#2490 [Fix] check if `compinit` is called before calling it
  bash_completion
Labels: shell: zsh
