Repository nvm-sh/nvm, pull requests merged in 2021-03, with the labels that each got.

#2390 added parallel build support for obsd
  nvm.sh
Labels: OS: FreeBSD / OpenBSD, installing node

#2462 [Fix] `nvm_alias`: ensure `lts/-1` returns the one before `lts/*`
  nvm.sh
  test/fast/Unit tests/nvm_alias LTS-N
Labels: bugs

#2202 Troubleshoot without closing the current shell.
  README.md
Labels: informational, installing nvm

#2466 Update source command to include s in zsh
  README.md
Labels: informational

#2470 Clarify the M1 shell instructions
  README.md
Labels: OS: Mac OS, informational
