Repository nvm-sh/nvm, pull requests merged in 2021-02, with the labels that each got.

#2431 [readme] quote asterisk in shell command on `--latest-npm` example
  README.md
Labels: informational

#2436 [readme] Update M1 macOS troubleshooting instructions
  README.md
Labels: OS: Mac OS, informational, installing node

#2400 [readme] add install error tips
  README.md
Labels: informational, installing nvm, shell: zsh

#2442 [readme] update `cdnvm` implementation
  README.md
Labels: informational

#2439 [New] `install`: add `-b` flag to skip building from source
  nvm.sh
  test/fast/Unit tests/nvm_install_binary_nosource
  test/installation_node/install from binary with binary flag set
Labels: feature requests, installing node
