Repository nvm-sh/nvm, pull requests merged in 2021-09, with the labels that each got.

#2584 Add specific permissions to workflows under .github/workflows
  .github/workflows/latest-npm.yml
  .github/workflows/lint.yml
  .github/workflows/rebase.yml
  .github/workflows/release.yml
  .github/workflows/require-allow-edits.yml
  .github/workflows/shellcheck.yml
  .github/workflows/toc.yml
  .github/workflows/windows-npm.yml
Labels: testing

#2585 [Fix] `bash_completion`: be robust when `cd` is overridden
  bash_completion
Labels: shell alias clobbering

#2604 updated automatic call script for bash
  README.md
Labels: shell: bash/sh, informational

#2517 fixed small typo afew to a few
  README.md
Labels: informational

#1471 [Tests] Print all shell version in Travis CI
  .travis.yml
Labels: testing

#1343 [readme] Add quick intro to `nvm`
  README.md
Labels: informational
