Repository nvm-sh/nvm, pull requests merged in 2022-12, with the labels that each got.

#2933 update test data for node 18 lts release
  test/fast/Unit tests/mocks/LTS_names.txt
  test/fast/Unit tests/mocks/lts-star.txt
  test/fast/Unit tests/mocks/nodejs.org-dist-index.tab
  test/fast/Unit tests/mocks/nodejs.org-download-nightly-index.tab
  test/fast/Unit tests/mocks/nvm ls-remote lts.txt
  test/fast/Unit tests/mocks/nvm ls-remote node.txt
  test/fast/Unit tests/mocks/nvm ls-remote.txt
  test/fast/Unit tests/mocks/nvm_ls_remote LTS.txt
  test/fast/Unit tests/mocks/nvm_ls_remote nightly.txt
  test/fast/Unit tests/mocks/nvm_ls_remote stable nightly.txt
  test/fast/Unit tests/mocks/nvm_ls_remote stable.txt
  test/fast/Unit tests/mocks/nvm_ls_remote.txt
  test/fast/Unit tests/mocks/nvm_make_alias LTS alias calls.txt
  test/fast/Unit tests/mocks/nvm_print_implicit_alias remote stable nightly.txt
  test/fast/Unit tests/mocks/nvm_print_implicit_alias remote stable.txt
Labels: testing

#2961 added WSL Troubleshooting and provided a solution to a common problem (fixed typos)
  README.md
Labels: OS: windows, installing node, informational

#2791 Improve contributors documentation
  CONTRIBUTING.md
Labels: informational

#2989 [tests] Update urchin project link
  README.md
Labels: testing
