Repository nvm-sh/nvm, pull requests merged in 2022-10, with the labels that each got.

#2729 [Docs] Add note about creating `.bashrc` file *as well as* `.bash_profile`
  README.md
Labels: shell: bash/sh, informational

#2823 [readme] Fix Git Install instruction list structure
  README.md
Labels: informational

#2840 [readme] cdnvm(): handle failed dir change
  README.md
Labels: informational

#2861 [readme] Fix Ansible Linting Errors
  README.md
Labels: informational

#2874 [readme] optimize calling of `nvm version` in zsh
  README.md
Labels: shell: zsh, informational

#2896 [readme] Update Alpine Linux Section
  README.md
Labels: informational

#2892 [Fix] `install.sh`: support `~/.zprofile`
  install.sh
  test/install_script/nvm_detect_profile
  test/install_script/nvm_profile_is_bash_or_zsh
Labels: shell: zsh, installing nvm: profile detection

#2827 [perf] `nvm_print_versions`: re-implement using awk
  nvm.sh
Labels: performance
