Repository nvm-sh/nvm, pull requests merged in 2023-10, with the labels that each got.

#3217 [Tests] fix filename typo
  test/slow/nvm use/Running 'nvm use' with nvmrc containing not installed version
Labels: testing

#3215 [readme] missing parenthesis
  README.md
Labels: informational, hacktoberfest-accepted

#3221 [readme] add section on bare `nvm install`
  README.md
Labels: informational
