Repository nvm-sh/nvm, pull requests merged in 2025-02, with the labels that each got.

#2541 [readme] fnm -> nvm.fish
  README.md
Labels: shell: fish, informational

#3469 [readme] remove `avn` from readme
  README.md
Labels: informational

#2318 [readme] add docker tips
  Dockerfile
  README.md
Labels: informational

#2241 [readme] Update shell profile file install notes
  README.md
Labels: informational, installing nvm: profile detection

#3052 [readme] add note about reloading zshrc after editing
  README.md
Labels: shell: zsh, informational

#2670 [readme] note zsh-nvm's AUTO_USE option
  README.md
Labels: shell: zsh, informational

#3507 📝 update copyright notice
  README.md
Labels: informational

#3470 [Tests] Migrate slow test suite from Travis CI
  .github/workflows/tests.yml
  .travis.yml
Labels: testing

#3476 [Tests] migrate `installation_iojs` test suite to GitHub Actions
  .github/workflows/tests.yml
  .travis.yml
Labels: testing

#3479 [readme] fix `--no-use` example
  README.md
Labels: informational
